import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Header } from '@/components/Header'
import { Footer } from '@/components/Footer'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <head>
        {/* Assegure-se de que o CSS global está sendo importado no <head> */}
        <link rel="stylesheet" href="/globals.css" />
      </head>
      <body className={`${inter.className}`}>
          <div
            className={`${inter.className} flex flex-col justify-between h-full items-center min-h-screen`}
          >
            <Header />
            <main className="flex-grow h-full relative max-w-6xl w-full mx-auto">
              {children}
            </main>
            <Footer />
          </div>
      </body>
    </html>
  )
}
